import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Blog from "../components/Blog";
import Content from "../components/Content";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Opinions from "../components/Opinions";
import Team from "../components/Team";
import TopBar from "../components/TopBar";
import Voice from "../components/Voice";
import { opinions } from "./../content/opinions";

const Home: NextPage = () => {
  return (
    <div className='relative'>
      <Head>
        <title>Adwokat Twoje Miasto</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
        {/* <link
          href='https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;500;600;700&family=Raleway:wght@400;500;600;700&display=swap'
          rel='stylesheet'
        /> */}
      </Head>
      <TopBar />
      <Header />
      <Content />
      <Voice />
      <Team />
      <Blog />
      <Opinions opinions={opinions} />
      <Footer />
    </div>
  );
};

export default Home;
